# Generated by Django 5.1.5 on 2025-02-02 18:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_answer_alter_faq_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='answer_bn'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='answer_hi'),
        ),
    ]
